#

the same thing we are reading from bitbucket

in the case of a debug replay we might go to prod box copy the layout styructure and includew this because if we are debugging a prod instancve we'd need to start it using the same config values, we woudl also change PRD to DEV or somethign so it does no actually send.  

If we wanted to replay the data but have log=debug same idea and modify this here
