deploy {
  instances = [
    {
      name = "shard-a"
      host = "flockr-fedora-shard-a"
      port = "22"
      login = "flockr"
      base_dir = "/apps/flockr"
      identity_file = "/home/flockr/.ssh/id_ed25519"
    },
    {
      name = "shard-b"
      host = "flockr-fedora-shard-b"
      port = "22"
      login = "flockr"
      base_dir = "/apps/flockr"
      identity_file = "/home/flockr/.ssh/id_ed25519"
    },
    {
      name = "shard-c"
      host = "flockr-fedora-shard-c"
      port = "22"
      login = "flockr"
      base_dir = "/apps/flockr"
      identity_file = "/home/flockr/.ssh/id_ed25519"
    },
    {
      name = "shard-d"
      host = "flockr-fedora-shard-d"
      port = "22"
      login = "flockr"
      base_dir = "/apps/flockr"
      identity_file = "/home/flockr/.ssh/id_ed25519"
    },
    {
      name = "shard-e"
      host = "flockr-fedora-shard-e"
      port = "22"
      login = "flockr"
      base_dir = "/apps/flockr"
      identity_file = "/home/flockr/.ssh/id_ed25519"
    }
  ]
}
